### PR TITLE
Added a client for Delphi

### PR DESCRIPTION
**Pull request by kurenkovk**
\clients\delphi\github.com\PyBridge\PBRedisClient

### CODE REVIEW

**Comment by kurenkovk** [comment]
Is it a wrong branch to post new clients? Should I use a **new-structure** branch?

**Comment by kurenkovk** [comment]
@itamarhaber 
Feel free to cancel the PR and roll out the correct version if some information is incorrect, e.g. the JSON structure or the data therein. I did not add the "recommended" flag as i suppose it is set by the administration.

**Comment by itamarhaber** [comment]
Hi @kurenkovk - this will be merged, sorry for the delay

**Comment by PBkkurenkov** [comment]
@oranagra  
Feel free to contact me if you have issues with the Delphi component.

**Comment by itamarhaber** [comment]
Hi @kurenkovk @PBkkurenkov 

I'm sorry, but we can't accept this PR since the project appears closed-source, whereas this website is heavily biased otherwise.

**Comment by kurenkovk** [comment]
Ok, thank you for clarification!

**Pull request closed without merging**
