### PR TITLE
Update for multiparam config set.

### PR DESCRIPTION
**Pull request by yoav-steinberg**
Update `CONFIG SET` docs given https://github.com/redis/redis/pull/9748

### CODE REVIEW

**Comment by yoav-steinberg** [comment]
Pending for https://github.com/redis/redis/pull/9656 to be merged so we won't override the commands.json modifications in this pr.

**Review by itamarhaber — APPROVED** [review]

**Comment by yoav-steinberg** [comment]
@itamarhaber I'd like to merge this bug I'd like you thumbs up on me deleting all that stuff about `save` and byte size notation which seemed irrelevant and obsolete.
Also there's a reference to the v6.0 _redis.conf_ file in this doc which I think we should change to simply reference the latest _redis.conf_ in unstable since our docs are always in sync with _unstable_ and not with a specific version. WDYT?

**Comment by itamarhaber** [comment]
I approved after thinking about the save removal (+1) and trying to find when the kb/mb was added (went as far as 2.2) but couldn't (so another +1). As for the link, makes sense to me - adding it and merging.

(also note that I added a history section for this change :))

**Comment by itamarhaber** [comment]
Coming to rethink about it, maybe we should keep the save note for the sake of users coming with less-than-7 versions.

**Comment by yoav-steinberg** [comment]
> Coming to rethink about it, maybe we should keep the save note for the sake of users coming with less-than-7 versions.

I think there's not reason since the change from pre-7, in that respect, is in the config file not in `config set`. So if you're pre 7 and trying to configure your redis's `save` you should read the relevant comments in `redis.conf`. Perhaps we can add a note about how the documentation in `redis.conf` changes from version to verion? I'll try to push something, let me know what you think.

**Review by itamarhaber — APPROVED** [review]
LGTM

**Pull request merged**
