### PR TITLE
Latency trouble shooting

### PR DESCRIPTION
**Pull request by pizhenwei**
Add document for latency trouble shooting:
* Add 'disable-thp' into latency.md, reference [redis change](https://github.com/redis/redis/commit/a9c06021498444b8d785066a2fae7d49693721dc).
* Document 'Latency induced by reading smaps/smaps_rollup', reference [atop change](https://github.com/Atoptool/atop/commit/604b563a223130d9bcce3d3358537a6c5ce05e7a).
* Introduce [tcprtt](https://github.com/iovisor/bcc/blob/master/tools/tcprtt.py) to trace TCP latency,

### CODE REVIEW

**Comment by itamarhaber** [comment]
Hello @pizhenwei 

Thanks for this contribution. Before reviewing it thoroughly, I'd like to understand why this should be included in the docs instead of other perf tools/metrics/etc.

@filipecosta90 please feel free to jump in

**Comment by pizhenwei** [comment]
Hi @itamarhaber 

I read docs from [redis.io](https://redis.io/docs/reference/optimization/latency/), followed the 'Edit this page' button, and added these changes in this PR.
It's the first time I've tried to contribute to redis doc, if anything gets wrong, please correct me, thanks!

**Comment by pizhenwei** [comment]
Hi @itamarhaber 
Could you please give me any hint, should I move any documents into another document or directory?

**Comment by pizhenwei** [comment]
@itamarhaber PING!

**Comment by itamarhaber** [comment]
+PONG
nothing is wrong with the contribution (thanks and congrats on your first!) per se. I'm not a performance engineer/admin so I'm having difficulties evaluating these tips. I'm also wondering whether there are other, perhaps even more useful, tips that we want to include. Therefore my question :)

@filipecosta90 thoughts?

**Comment by pizhenwei** [comment]
@filipecosta90 PING!

Hi, I edited the top comment and added link.

**Comment by pizhenwei** [comment]
Hi, @oranagra 

I hope I'm not disturbing you...
This seems to have been ignored, could you please take a look at this?

**Comment by oranagra** [comment]
I'm not familiar with some of these details myself either.. i'll try to grab the attention of someone who does..
but also, i guess that for the case of redis.io docs, it wouldn't be a terrible idea to include these details, even if they're slightly misplaced...
maybe it'll help someone, and maybe some future edit will change / improve them...

**Review by ushachar — COMMENTED** [review]
The tools & /proc paths mentioned here are Linux specific and relate more to general system debugging then something very Redis specific - not sure they belong in the Redis documentation.

**Comment by nermiller** [comment]
@ushachar, this information is available in Red Hat Linux training and docs. I recommend not adding this information to our docs as third-party docs may change.

**Comment by pizhenwei** [comment]
Hi, @nermiller @ushachar @itamarhaber 

From your suggestions, closing this PR seems right. Thanks for your suggestions!

**Pull request closed without merging**
