### PR TITLE
Add concurrent note for Rate limiter Pattern

### PR DESCRIPTION
**Pull request by atealxt**
PR for [issue 777](https://github.com/antirez/redis-doc/issues/777).

### CODE REVIEW

**Comment by badboy** [comment]
I'm not too happy with the current wording.
Plus, you escaped quotes in the code. I don't think this is necessary.

**Comment by atealxt** [comment]
Could you please provide more specific? We can adjust texts if basic idea is agreed.

**Comment by badboy** [comment]
For once, it is not proper English. But I don't have the time or energy right now to fix it.

**Comment by nermiller** [comment]
Closing as stale.

**Pull request closed without merging**
