### PR TITLE
Clarify the importance of CLUSTER SETSLOT NODE to dst before src

### PR DESCRIPTION
**Pull request by zuiderkwast**
See redis/redis#7116

### CODE REVIEW

**Review by enjoy-binbin — APPROVED** [review]
good job, it also solved one of my doubts

**Comment by zuiderkwast** [comment]
@enjoy-binbin Thanks. Do you think we should fix redis-cli to use this order too? Right now it sends SETSLOTS NODE to all nodes in any order.

**Comment by enjoy-binbin** [comment]
@zuiderkwast yes, i think we can fix it, looks like it's easy to fix

**Comment by zuiderkwast** [comment]
@enjoy-binbin See redis/redis#10381. (It also fixes another problem.)

**Pull request merged**
