### PR TITLE
Update wordlist

### PR DESCRIPTION
**Pull request by sav-norem**
update wordlist to include commands for tabbed examples for lists and strings

### CODE REVIEW

**Comment by sav-norem** [comment]
@dwdougherty could you review this?

**Review by dwdougherty — COMMENTED** [review]
This looks okay, but I don't have experience with the spell checker. If you ran it by yourself, did everything look okay? If so, you're probably good.

**Comment by sav-norem** [comment]
yea it works for me!

**Comment by dwdougherty** [comment]
That's great.

**Review by dwdougherty — APPROVED** [review]

**Comment by dwdougherty** [comment]
Would you please also add the work "nx" to your PR? We saw that when working on committing your string PR.

**Comment by sav-norem** [comment]
@dmaier-redislabs added the "nx" keyword - I'm hopeful if we can get this wordlist updated, the geospatial and list updates will be ready to go as well. sets data type is just about ready so I went ahead and added those shortcodes as well

**Review by dwdougherty — APPROVED** [review]
This PR doesn't require a local test build, but it should take care of the extant spellcheck issues.

**Review by dmaier-redislabs — APPROVED** [review]

**Pull request merged**
