### PR TITLE
extra spaces correction in sadd example

### LINKED ISSUE #1712: [BUG]Typo in tuturial website
In https://redis.io/topics/data-types-intro:

>  sadd deck C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 CJ CQ CK
   D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 DJ DQ DK H1 H2 H3
   H4 H5 H6 H7 H8 H9 H10 HJ HQ HK S1 S2 S3 S4 S5 S6
   S7 S8 S9 S10 SJ SQ SK
   (integer) 52 

image

There should be fewer spaces at the beginning of the second line (before (integer 52)). This is a very small bug :D

### PR DESCRIPTION
**Pull request by enjoy-binbin**
Fixes #1712

### CODE REVIEW

**Review by yoav-steinberg — COMMENTED** [review]
Thanks @enjoy-binbin, this is what I had in mind.

Before I merge I just want to confirm you tested this by running _redis-io_ locally to see this produces the right result?

**Comment by enjoy-binbin** [comment]
Not yet.. i do not have the redis-io env. and i am bother to install it.
So if you have the env and some free times, can you test it for me? or i try to install the env later

**Review by yoav-steinberg — APPROVED** [review]
Ok, verified myself. I'll merge.
Thanks.
In general I'd like you to verify these PRs on a local _redis-io_ setup (it's pretty simple to get it running, just make sure you have a _redis-server_ running locally with default port and no password). Once I merge a PR it auto updates the official site so we need to be sure it doesn't break anything.

**Comment by itamarhaber** [comment]
Hopefully, soon, the website will be easier to deploy/run locally.

**Pull request merged**
