### PR TITLE
Fix LIMIT index error in ZRANGEBYLEX command of indexes.md.

### PR DESCRIPTION
**Pull request by huangzhw**
Fix LIMIT index error in ZRANGEBYLEX command of indexes.md.

Additionally fix one item in ZRANGEBYLEX output which should
not exist.

Fix https://github.com/redis/redis/issues/8738

### CODE REVIEW

**Review by cheind — CHANGES_REQUESTED** [review]
Thanks for the PR and spotting the error with bananas :) My original  report was about line number 351.

```
ZRANGEBYLEX myindex [mykey: + LIMIT 1 1
    1) "mykey:myvalue"
```

which is not addressed by this PR.

**Comment by huangzhw** [comment]
@cheind Thanks. I think line 287 should also be updated. Do you think so?

**Comment by cheind** [comment]
Yes I think, but there is probably more: Looking at the specific example

```
    ZRANGEBYLEX myindex "[banana:" + LIMIT 1 10
    1) "banana:123"
    2) "banahhh:1"
    3) "banned user:49"
    4) "banning:89"
```
 
I wonder about the returned items, item 2 is lexicographically before banana and should not be returned

```
127.0.0.1:6379> zadd myindex 0 banana:123
(integer) 1
127.0.0.1:6379> zadd myindex 0 banahhh:1
(integer) 1
127.0.0.1:6379> zadd myindex 0 banned user:49
(error) ERR syntax error
127.0.0.1:6379> zadd myindex 0 'banned user:49'
(integer) 1
127.0.0.1:6379> zadd myindex 0 'banning:89'
(integer) 1
127.0.0.1:6379> ZRANGEBYLEX myindex "[banana:" + LIMIT 1 10
1) "banned user:49"
2) "banning:89"
127.0.0.1:6379> ZRANGEBYLEX myindex "[banana:" + LIMIT 0 10
1) "banana:123"
2) "banned user:49"
3) "banning:89"
127.0.0.1:6379>
```

**Comment by huangzhw** [comment]
Maybe the output is made by human input. Fixed.

**Review by itamarhaber — APPROVED** [review]

**Comment by itamarhaber** [comment]
Thanks @huangzhw and @cheind for finding and fixing this nastiness - merging

**Pull request merged**
