### PR TITLE
configuration for 7.0 added

### PR DESCRIPTION
**Pull request by masteryyh**

### CODE REVIEW

**Comment by masteryyh** [comment]
any update on this? @zuiderkwast @banker

**Review by enjoy-binbin — APPROVED** [review]
the ci was removed in https://github.com/redis/redis-doc/pull/1934
so i think we can process it (or any other PRs...)
@zuiderkwast i guess you can try to handle those `to-be-merged` PRs when you have time

**Comment by zuiderkwast** [comment]
I tried restarting the CI jobs, but it still fails. @masteryyh I think you need to rebase (or merge unstable into this branch) to include the fixes for the CI build. Hopefully it will make it green.

**Comment by oranagra** [comment]
i don't see why we need to rebase or resolve the CI error in order to merge this boilerplate change.

**Comment by zuiderkwast** [comment]
> i don't see why we need to rebase or resolve the CI error in order to merge this boilerplate change.

Not necessary for this one, but what about all the other PRs which are red? There are quite a few. I don't know what the CI does apart from spell check.

**Comment by oranagra** [comment]
If it's not helping us, it's standing in our way and we can ignore it IMHO. I.e. Better merge things with spelling mistakes than get into stagnation. 

Anyway, if the CI is now fixed, you can trigger a real re-run by editing the PR (add and remove a space, no need for rebase) since the CI runs on the merge result with the master Sha that existed when the PR was last edited (last push) . 

P. s. It's not that I think it was wrong to ask the opener to do that, it's just that I happen to look yesterday and was stunned by the big number of PRs marked to be merged and no real reason not to merge them.. So I spent some time merging trivial ones

**Pull request merged**
