### PR TITLE
redis 7.0.3 auto generated files

### PR DESCRIPTION
**Pull request by oranagra**

### CODE REVIEW

**Comment by oranagra** [comment]
```
Error: docs/reference/modules/modules-api-ref.md
    343:43-343:60  warning  `RedisModule_Yield` is misspelt                   retext-spell  retext-spell
     500:1-500:26  warning  `RedisModule_CreateCommand` is misspelt           retext-spell  retext-spell
    501:23-501:48  warning  `RedisModule_CreateCommand` is misspelt           retext-spell  retext-spell
     502:8-502:34  warning  `RedisModule_SetCommandInfo` is misspelt          retext-spell  retext-spell
     505:1-505:26  warning  `RedisModule_CreateCommand` is misspelt           retext-spell  retext-spell
    505:28-505:61  warning  `RedisModule_IsKeysPositionRequest` is misspelt   retext-spell  retext-spell
    505:66-505:95  warning  `RedisModule_KeyAtPosWithFlags` is misspelt       retext-spell  retext-spell
  4623:41-4623:75  warning  `RedisModule_CreateStringFromString` is misspelt  retext-spell  retext-spell
```
@itamarhaber how do you suggest to resolve this?

**Comment by itamarhaber** [comment]
@slorello89 feel free to jump in

**Comment by slorello89** [comment]
4 options:

1. Properly escape these with markdown in redis, then re-generate this file. All of these instances appear to be in non-code sections, so it expects them to either be spelled correctly or have an exception added to the wordlist.
2. Add each individual item to the [wordlist](https://github.com/redis/redis-doc/blob/master/wordlist)
3. Add a single Regex to match all the cases to the wordlist
4. Exclude this file from consideration by the spellchecker by changing the spellchecker configuration. This file in particular is a bit painful because it requires an update in redis, followed by a separate PR here, so this could be a viable option. This would just involve adding ` - '!docs/reference/modules/modules-api-ref.md'` to the `.spellcheck.yml` file at the root of redis-doc

**Comment by itamarhaber** [comment]
Took option 3, lets also do 1 and 4.

**Pull request merged**
