### PR TITLE
Update context parameter in go.md

### PR DESCRIPTION
**Pull request by AnandaIlyasa**
ctx parameter is not yet initialized in the examples so I pass the context.Background()

### CODE REVIEW

**Comment by nermiller** [comment]
@uglide please review this issue. Thank you!

**Review by nermiller — APPROVED** [review]
LGTM

**Review by nermiller — APPROVED** [review]

**Comment by nermiller** [comment]
Thanks for contributing, @AnandaIlyasa. We appreciate you!

**Comment by AnandaIlyasa** [comment]
> Thanks for contributing, @AnandaIlyasa. We appreciate you!

my pleasure

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Pull request merged**
