### PR TITLE
Cleanup erlang clients that are not maintained

### PR DESCRIPTION
**Pull request by NikolaBorisov**
Removing Erlang clients that are not maintained in the last 5 years.

### CODE REVIEW

**Comment by NikolaBorisov** [comment]
@zuiderkwast Here is PR that deletes the 2 projects that didn't have any commits in the last 5 years.

**Review by zuiderkwast — APPROVED** [review]

**Comment by zuiderkwast** [comment]
Good! Only one thing: The commit message and the PR title has a misspelled "elrang".

**Comment by NikolaBorisov** [comment]
> Good! Only one thing: The commit message and the PR title has a misspelled "elrang".

Will fix.

**Comment by NikolaBorisov** [comment]
> Good! Only one thing: The commit message and the PR title has a misspelled "elrang".

Fixed

**Comment by zuiderkwast** [comment]
@NikolaBorisov I merged your other PR (and some other PRs) and now there is a merge confligt. Can you rebase, please?

**Comment by NikolaBorisov** [comment]
> @NikolaBorisov I merged your other PR (and some other PRs) and now there is a merge confligt. Can you rebase, please?

@zuiderkwast done

**Pull request merged**
